### ISSUE TITLE
Remove MSCVR120.dll dependency?

### ISSUE THREAD

**Issue by AndhikaWB** [crazy-max/IconsRefresh#1]
Is it possible to remove MSCVR120.dll dependency from the exe file completely? Putting the dll file into the exe directory works, but inefficient for me because it needs 2 files instead of one. Might seems weird but I don't want to install VC Redist unless I really need it.

**Comment by crazy-max** [comment]
@AndhikaWB Yes I think I can remove this dependency. I keep you in touch.

**Comment by AndhikaWB** [comment]
Thank you, I will be waiting then.

**Comment by crazy-max** [comment]
@AndhikaWB Should be ok with the latest release ;)
