### ISSUE TITLE
Virus alert

### ISSUE THREAD

**Issue by djbrandt-fits** [crazy-max/IconsRefresh#4]
Scan type: Auto-Protect Scan
Event: Risk Found!
Security risk detected: Heur.AdvML.B
File: C:\Users\********\Downloads\IconsRefresh.exe
Location: C:\Users\********\Downloads
Computer: *****40132671
User: ********
Action taken: Pending Side Effects Analysis : Access denied

Date found: Montag, 25. November 2019  14:36:47

**Comment by crazy-max** [comment]
What antivirus do you use ?

As I said in [an other project](https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper), detections found by VirusTotal scan are generic. Most likely based on a heuristic detection. Heuristics are more prone to false-positive detections.

This [happens quite often](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20antivirus) with programs written in [Golang](https://golang.org/). The best you can do is to report this to your Antivirus software vendor.

I have sent the file to BitDefender and Microsoft already and they said it's a false positive.

**Comment by djbrandt-fits** [comment]
Hi, thx for your comment. As company, we are using Symantec Enterprise Protection 12. I will inform our security department.
