### ISSUE TITLE
Why is Icons Refresh detected as malware?

### ISSUE THREAD

**Issue by sjkorvin** [crazy-max/IconsRefresh#5]
I had downloaded and run Icons Refresh and it did not solve my issue of a missing UWP desktop icon. Clearing the Windows 10 icon cache manually had solved my issue. When I had run Clear Icons Cache by Leo Davidson after running Icons Refresh, Clear Icons Cache had displayed a message saying that there was no icon cache, so perhaps, Icons Refresh had deleted it.

I'm a little nervous because Icons Refresh is detected by so many anti-malware engines and when I had seen a system page in Microsoft Edge saying that my network settings had changed, I had gotten worried that Icons Refresh had done something to my system. 

Why is Icons Refresh detected by so many anti-malware engines?

**Comment by crazy-max** [comment]
@sjkorvin

> I had downloaded and run Icons Refresh and it did not solve my issue of a missing UWP desktop icon. Clearing the Windows 10 icon cache manually had solved my issue. When I had run Clear Icons Cache by Leo Davidson after running Icons Refresh, Clear Icons Cache had displayed a message saying that there was no icon cache, so perhaps, Icons Refresh had deleted it.

Maybe an issue with the event notification. Will take a look on this.

> I'm a little nervous because Icons Refresh is detected by so many anti-malware engines

Like stipulated in #4 this happens quite often with programs written in Golang. The best you can do is to report this to your Antivirus software vendor.

> ...and when I had seen a system page in Microsoft Edge saying that my network settings had changed, I had gotten worried that Icons Refresh had done something to my system.

As you can see in the source code, the app only calls [`SHChangeNotify`](https://github.com/crazy-max/IconsRefresh/blob/abeabadbd4066ae54e1f6385cd920190d6f1b7d9/main.go#L21) and [`SendMessageTimeoutW`](https://github.com/crazy-max/IconsRefresh/blob/abeabadbd4066ae54e1f6385cd920190d6f1b7d9/main.go#L28).  It only notifies notifies the system of an event, nothing else that could affect your system.
